name: gitleaks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  scan:
    name: Scan for secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gitleaks
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/scripts/install.sh | bash -s -- v8.18.2

      - name: Run gitleaks
        shell: bash
        run: |
          ./gitleaks detect \
            --config=gitleaks.toml \
            --source . \
            --redact \
            --no-banner
